name: Deploy to BACKEND_EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug key lines
        run: |
          echo "${{ secrets.BACK_EC2_KEY }}" > key.pem
          wc -l key.pem

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BACK_EC2_HOST }}
          username: ${{ secrets.BACK_EC2_USER }}
          key: ${{ secrets.BACK_EC2_KEY }}
          script: |
            cd ~/power/BE
            ./deploy_Back.sh
